[2024-04-23T14:20:08.711+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.extract manual__2024-04-23T14:20:07.888242+00:00 [queued]>
[2024-04-23T14:20:08.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.extract manual__2024-04-23T14:20:07.888242+00:00 [queued]>
[2024-04-23T14:20:08.717+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-23T14:20:08.723+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-04-23 14:20:07.888242+00:00
[2024-04-23T14:20:08.726+0000] {standard_task_runner.py:57} INFO - Started process 1376 to run task
[2024-04-23T14:20:08.728+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'extract', 'manual__2024-04-23T14:20:07.888242+00:00', '--job-id', '37', '--raw', '--subdir', '/opt/airflow/dags/dags-example/etl.py', '--cfg-path', '/tmp/tmpetm6_fr3']
[2024-04-23T14:20:08.729+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask extract
[2024-04-23T14:20:08.761+0000] {task_command.py:415} INFO - Running <TaskInstance: etl.extract manual__2024-04-23T14:20:07.888242+00:00 [running]> on host 44f2c0439e04
[2024-04-23T14:20:08.809+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T14:20:07.888242+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T14:20:07.888242+00:00'
[2024-04-23T14:20:09.145+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags-example/etl.py", line 31, in extract
    cleaned_data_out = save_to_local(data, timestamp)
  File "/opt/airflow/./dags/helper/module_1_extract.py", line 75, in save_to_local
    pd_df.to_csv(local_path_csv, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/raw_116532_1713882009.csv'
[2024-04-23T14:20:09.162+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl, task_id=extract, execution_date=20240423T142007, start_date=20240423T142008, end_date=20240423T142009
[2024-04-23T14:20:09.170+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task extract ([Errno 13] Permission denied: '/raw_116532_1713882009.csv'; 1376)
[2024-04-23T14:20:09.212+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-23T14:20:09.242+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
