[2024-04-23T15:18:03.213+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_scd2.run_sql manual__2024-04-23T15:18:02.315949+00:00 [queued]>
[2024-04-23T15:18:03.217+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_scd2.run_sql manual__2024-04-23T15:18:02.315949+00:00 [queued]>
[2024-04-23T15:18:03.218+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-23T15:18:03.226+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): run_sql> on 2024-04-23 15:18:02.315949+00:00
[2024-04-23T15:18:03.230+0000] {standard_task_runner.py:57} INFO - Started process 886 to run task
[2024-04-23T15:18:03.232+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'db_scd2', 'run_sql', 'manual__2024-04-23T15:18:02.315949+00:00', '--job-id', '54', '--raw', '--subdir', '/opt/airflow/dags/dags-example/db_scd2.py', '--cfg-path', '/tmp/tmpldcy45fz']
[2024-04-23T15:18:03.234+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask run_sql
[2024-04-23T15:18:03.265+0000] {task_command.py:415} INFO - Running <TaskInstance: db_scd2.run_sql manual__2024-04-23T15:18:02.315949+00:00 [running]> on host 455dffaa18e2
[2024-04-23T15:18:03.310+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='db_scd2' AIRFLOW_CTX_TASK_ID='run_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T15:18:02.315949+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T15:18:02.315949+00:00'
[2024-04-23T15:18:03.316+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags-example/db_scd2.py", line 82, in run_sql
    connection.commit()
AttributeError: 'Connection' object has no attribute 'commit'
[2024-04-23T15:18:03.322+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=db_scd2, task_id=run_sql, execution_date=20240423T151802, start_date=20240423T151803, end_date=20240423T151803
[2024-04-23T15:18:03.327+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task run_sql ('Connection' object has no attribute 'commit'; 886)
[2024-04-23T15:18:03.331+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-23T15:18:03.343+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
