[2024-04-23T13:32:11.020+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_setting_v1.get_info manual__2024-04-23T13:32:10.353712+00:00 [queued]>
[2024-04-23T13:32:11.024+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_setting_v1.get_info manual__2024-04-23T13:32:10.353712+00:00 [queued]>
[2024-04-23T13:32:11.024+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-23T13:32:11.029+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): get_info> on 2024-04-23 13:32:10.353712+00:00
[2024-04-23T13:32:11.031+0000] {standard_task_runner.py:57} INFO - Started process 374 to run task
[2024-04-23T13:32:11.033+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_setting_v1', 'get_info', 'manual__2024-04-23T13:32:10.353712+00:00', '--job-id', '22', '--raw', '--subdir', '/opt/airflow/dags/dags-example/first_dag.py', '--cfg-path', '/tmp/tmpcv0fcuto']
[2024-04-23T13:32:11.035+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask get_info
[2024-04-23T13:32:11.065+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_setting_v1.get_info manual__2024-04-23T13:32:10.353712+00:00 [running]> on host 44f2c0439e04
[2024-04-23T13:32:11.114+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_setting_v1' AIRFLOW_CTX_TASK_ID='get_info' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T13:32:10.353712+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T13:32:10.353712+00:00'
[2024-04-23T13:32:11.115+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags-example/first_dag.py", line 15, in get_info
    print(1/0)
ZeroDivisionError: division by zero
[2024-04-23T13:32:11.122+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_setting_v1, task_id=get_info, execution_date=20240423T133210, start_date=20240423T133211, end_date=20240423T133211
[2024-04-23T13:32:11.129+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task get_info (division by zero; 374)
[2024-04-23T13:32:11.134+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-23T13:32:11.146+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
